# Generated by Django 5.1.4 on 2025-02-10 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
