# Generated by Django 5.1.6 on 2025-03-16 08:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.UUID('44662b3d-e5af-4bef-9212-7b8f0ddb8bbf'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bbd9574b-6062-4597-bcbb-7c98b9dbfca9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('71594238-41ea-45c9-9f5a-64f1bac687ca'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=50, unique=True)),
                ('available', models.BooleanField(default=False)),
                ('publication_date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_author', to='books.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_category', to='books.category')),
            ],
        ),
    ]
