# Generated by Django 5.1.6 on 2025-03-16 09:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_author_id_alter_category_id_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1a001fcc-11fa-46d9-abc6-ca35161d00a4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('355d2804-1a2a-4f90-a3a4-ea5db11ea816'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c916dfc5-56fc-473b-a670-6de9adf1f6dd'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('borrow_date', models.DateField(auto_created=True, editable=False)),
                ('id', models.UUIDField(default=uuid.UUID('efc667ce-b9c6-4554-b480-003c333b44d9'), editable=False, primary_key=True, serialize=False)),
                ('return_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='borrow_book', to='books.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_book_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
