# Generated by Django 5.1.6 on 2025-03-16 09:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_author_id_alter_book_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0ba6556d-d02a-4fd5-b69a-e772db0e51da'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6864bc65-2b15-4be7-9522-4fefa6da5407'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8fb2e4a4-0bbb-460d-896f-2dda85ed83e4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('72c80dfc-872d-4f48-879b-6fd7a3b46f90'), editable=False, primary_key=True, serialize=False),
        ),
    ]
