# Generated by Django 5.1.6 on 2025-03-16 09:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_author_id_alter_book_id_alter_book_isbn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0e735750-1ea7-4b51-98ac-dec4f8ce9573'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('30c63582-5dfd-41d4-93e1-e0c5fe6799a2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_book', to='books.book'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0cfaa721-1d50-4d0a-af38-7f339baa618f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9b90ec9c-53b8-4ab8-aa90-6c27116529da'), editable=False, primary_key=True, serialize=False),
        ),
    ]
