# Generated by Django 5.1.6 on 2025-03-16 09:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_author_id_alter_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.UUID('56e731a3-e193-472b-8a9c-906c411e07c6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1a5d60c4-a55f-4c7d-94ce-49035baa3b99'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c98e6b65-cc8c-4187-bd79-5dc8ad665741'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6cbce50c-2bf8-4d44-b4a9-b323d0f405e6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
